### ISSUE TITLE
Update markdown files

### ISSUE THREAD

**Issue by bonicim** [VOLTTRON/copier-poetry-volttron-agent#38]
Tasks:

* Remove CODE_OF_CONDUCT.md
* Update CONTRIBUTING.md with a message that they need to fill out the user contribution form at: https://www.eclipse.org/legal/ECA.php

**Comment by kefeimo** [comment]
@bonicim, @schandrika The content of `CONTRIBUTING.md` seems to need to update as well, (besides adding the message need to fill out the user contribution form at: https://www.eclipse.org/legal/ECA.php)

Since there is no `CONTRIBUTING.md` in volttron-listener-agent or volttron-core. I am going to use other option:

- volttron: https://github.com/VOLTTRON/volttron/blob/main/CONTRIBUTING.md

**Comment by kefeimo** [comment]
fixed by https://github.com/VOLTTRON/copier-poetry-volttron-agent/pull/47
manually closed
